name: Test Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  test_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run Reusable Workflow
        env:
          TEST_SECRET: ${{ secrets.REUSABLE_SECRET }}
          TEST_VARIABLE: ${{ vars.REUSABLE_VARIABLE }}
          MESSAGE: ${{ inputs.message }}
        run: |
          echo "Input message: $MESSAGE"
          echo "Reusable variable test: $TEST_VARIABLE"
          echo "Reusable secret test: $TEST_SECRET"
