name: Test Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      REUSABLE_SECRET:
        required: false

jobs:
  test_reusable_workflow:
    runs-on: ubuntu-latest
    environment: non-prod
    steps:
      - name: Run Reusable Workflow
        env:
          TEST_SECRET: ${{ secrets.REUSABLE_SECRET }}
          MESSAGE: ${{ inputs.message }}
        run: |
          echo "Input message: $MESSAGE"
          echo "Reusable secret test: $TEST_SECRET"
